name = "capacity-tracker"
main = "worker/src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "capacity_tracker_db"
database_id = "d80c5833-d572-4656-9ce6-b8900c2ca86b"
